<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tgm_grids"
 *
 * Auto generated by Extension Builder 2016-07-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Predefined Gridelements',
	'description' => 'Provides some frequently used gridelements with 2, 3 and 4 columns. Furthermore there is a fullwidth (.container) Mastergridelement which can be used only as toplevel element.',
	'category' => 'plugin',
	'author' => 'Steffen Thierock',
	'author_email' => 'st@teamgeist-medien.de',
	'state' => 'beta',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'gridelements' => '7.0.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);