<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "tgm_grids"
 *
 * Auto generated by Extension Builder 2016-07-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'TgM Grids',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Steffen Thierock',
	'author_email' => 'st@teamgeist-medien.de',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
			'gridelements' => '3.3.0',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);